# This is a basic workflow that is manually triggered

name: Deploy website

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    # Runs a single command using the runners shell. Based on https://raw.githubusercontent.com/xRealNeon/VuePagesAction/main/action.yml
    - name: Build site
      run: |
              ls
              cd hsb-union
              npm ci
              npm run build
              cd dist
              ln -s index.html 404.html
              git init
              git add -A
              git commit -m '${{ inputs.gitmsg }}'
              https://github.com/hsb-union/hsb-union.github.io.git
              git push -f https://hsb-union:${{ GITHUB_TOKEN }}@github.com/hsb-union/hsb-union.github.io.git master:gh-pages
